# -*- coding: utf-8 -*-
"""Workshop-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhWvvE7Bvv6-PLIVtaF9XH3izcJqqMcs
"""

from google.colab import files

# Subir archivo candidates.csv
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('candidates.csv')
df.head()

import sqlite3
import pandas as pd

# ==========================================
# 1. EXTRACT
# ==========================================
csv_path = "candidates.csv"
df = pd.read_csv(csv_path)

# ==========================================
# 2. TRANSFORM
# ==========================================
# a. Data Cleaning
df["Seniority"] = df["Seniority"].fillna("Unknown")
df["Yoe"] = df["Yoe"].fillna(0)
df["Technical Interview"] = df["Technical Interview"].fillna(0)
df["Email"] = df["Email"].fillna("N/A")
df["Application Date"] = pd.to_datetime(df["Application Date"])

# b. Apply HIRED Rule (Code Challenge >= 7 AND Technical Interview >= 7)
df["is_hired"] = (
    (df["Code Challenge Score"] >= 7) & (df["Technical Interview"] >= 7)
).astype(int)

# c. Dimensions Creation
dim_candidate = (
    df[["First Name", "Last Name", "Email"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
dim_candidate["candidate_id"] = dim_candidate.index + 1

dim_country = pd.DataFrame({"country_name": df["Country"].unique()})
dim_country["country_id"] = dim_country.index + 1

dim_technology = pd.DataFrame({"technology_name": df["Technology"].unique()})
dim_technology["technology_id"] = dim_technology.index + 1

dim_seniority = pd.DataFrame({"seniority_name": df["Seniority"].unique()})
dim_seniority["seniority_id"] = dim_seniority.index + 1

dim_date = pd.DataFrame({"full_date": df["Application Date"].unique()})
dim_date["full_date"] = pd.to_datetime(dim_date["full_date"])
dim_date["year"] = dim_date["full_date"].dt.year
dim_date["month"] = dim_date["full_date"].dt.month
dim_date["day"] = dim_date["full_date"].dt.day
dim_date["date_id"] = dim_date.index + 1

# d. Fact Table Assembly
fact_df = df.merge(
    dim_candidate, on=["First Name", "Last Name", "Email"], how="left"
)
fact_df = fact_df.merge(
    dim_country, left_on="Country", right_on="country_name", how="left"
)
fact_df = fact_df.merge(
    dim_technology,
    left_on="Technology",
    right_on="technology_name",
    how="left",
)
fact_df = fact_df.merge(
    dim_seniority, left_on="Seniority", right_on="seniority_name", how="left"
)
fact_df = fact_df.merge(
    dim_date, left_on="Application Date", right_on="full_date", how="left"
)

fact_applications = fact_df[[
    "candidate_id",
    "country_id",
    "technology_id",
    "seniority_id",
    "date_id",
    "Yoe",
    "Code Challenge Score",
    "Technical Interview",
    "is_hired",
]].copy()

fact_applications.rename(
    columns={
        "Yoe": "yoe",
        "Code Challenge Score": "code_challenge_score",
        "Technical Interview": "technical_interview_score",
    },
    inplace=True,
)
fact_applications["application_id"] = fact_applications.index + 1

# ==========================================
# 3. LOAD TO DATA WAREHOUSE (SQLite)
# ==========================================
conn = sqlite3.connect("data_warehouse.db")

dim_candidate.to_sql("dim_candidate", conn, if_exists="replace", index=False)
dim_country.to_sql("dim_country", conn, if_exists="replace", index=False)
dim_technology.to_sql("dim_technology", conn, if_exists="replace", index=False)
dim_seniority.to_sql("dim_seniority", conn, if_exists="replace", index=False)
dim_date.to_sql("dim_date", conn, if_exists="replace", index=False)
fact_applications.to_sql(
    "fact_applications", conn, if_exists="replace", index=False
)

conn.close()
print(
    "✅ Proceso ETL completado con éxito. DW creado en 'data_warehouse.db'."
)

import sqlite3
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Conexión al Data Warehouse
conn = sqlite3.connect("data_warehouse.db")

# Estilo y configuración de la figura
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(15, 11))

# --- Graph A: Hires by Technology (Pie Chart) ---
df_tech = pd.read_sql_query(
    """
    SELECT dt.technology_name, COUNT(fa.application_id) AS total_hires
    FROM fact_applications fa
    JOIN dim_technology dt ON fa.technology_id = dt.technology_id
    WHERE fa.is_hired = 1
    GROUP BY dt.technology_name
    ORDER BY total_hires DESC
""",
    conn,
)

axes[0, 0].pie(
    df_tech["total_hires"],
    labels=df_tech["technology_name"],
    autopct="%1.1f%%",
    startangle=140,
)
axes[0, 0].set_title("Hires by Technology", fontsize=12, weight="bold")

# --- Graph B: Hires by Year (Horizontal Bar Chart) ---
df_year = pd.read_sql_query(
    """
    SELECT dd.year, COUNT(fa.application_id) AS total_hires
    FROM fact_applications fa
    JOIN dim_date dd ON fa.date_id = dd.date_id
    WHERE fa.is_hired = 1
    GROUP BY dd.year
    ORDER BY dd.year ASC
""",
    conn,
)

sns.barplot(
    data=df_year,
    x="total_hires",
    y="year",
    orient="h",
    ax=axes[0, 1],
    palette="Blues_r",
)
axes[0, 1].set_title("Hires by Year", fontsize=12, weight="bold")
axes[0, 1].set_xlabel("Total Hires")
axes[0, 1].set_ylabel("Year")

# --- Graph C: Hires by Seniority (Bar Chart) ---
df_seniority = pd.read_sql_query(
    """
    SELECT ds.seniority_name, COUNT(fa.application_id) AS total_hires
    FROM fact_applications fa
    JOIN dim_seniority ds ON fa.seniority_id = ds.seniority_id
    WHERE fa.is_hired = 1
    GROUP BY ds.seniority_name
    ORDER BY total_hires DESC
""",
    conn,
)

sns.barplot(
    data=df_seniority,
    x="seniority_name",
    y="total_hires",
    ax=axes[1, 0],
    palette="Blues_r",
)
axes[1, 0].set_title("Hires by Seniority", fontsize=12, weight="bold")
axes[1, 0].set_xlabel("Seniority Level")
axes[1, 0].set_ylabel("Total Hires")
axes[1, 0].tick_params(axis="x", rotation=45)

# --- Graph D: Hires by Country Over Years (Multiline Chart) ---
df_country = pd.read_sql_query(
    """
    SELECT dd.year, dc.country_name, COUNT(fa.application_id) AS total_hires
    FROM fact_applications fa
    JOIN dim_country dc ON fa.country_id = dc.country_id
    JOIN dim_date dd ON fa.date_id = dd.date_id
    WHERE fa.is_hired = 1
      AND dc.country_name IN ('USA', 'Brazil', 'Colombia', 'Ecuador')
    GROUP BY dd.year, dc.country_name
    ORDER BY dd.year ASC, dc.country_name
""",
    conn,
)

sns.lineplot(
    data=df_country,
    x="year",
    y="total_hires",
    hue="country_name",
    marker="o",
    ax=axes[1, 1],
    linewidth=2,
)
axes[1, 1].set_title("Hires by Country Over Years", fontsize=12, weight="bold")
axes[1, 1].set_xlabel("Year")
axes[1, 1].set_ylabel("Total Hires")

plt.tight_layout()
plt.savefig("kpi_dashboard_final.png", dpi=300)
plt.show()

conn.close()

from google.colab import files

files.download("kpi_dashboard_final.png")